model:
  model_id: diff_dec
  sample_size: [16,16]
  channels: 32
  latent_size: 8
  latent_channels: 128
  patch_size: 1

  n_layers: 14
  n_heads: 24
  d_model: 1536

  causal: false
  mimetic_init: false
  block_size: null

train:
  trainer_id: diffdec_dmd
  data_id: s3_cod_features
  data_kwargs:
    bucket_name: cod-raw-360p-30fs
    prefix: rgb-depth-flow
    include_flow: true
    include_depth: true

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-6
    betas: [0.9, 0.999]
    weight_decay: 0.01
    eps: 1.0e-8
  d_opt_kwargs:
    lr: 2.0e-6
    betas: [0.9, 0.999]
    weight_decay: 0.01
    eps: 1.0e-8

  scheduler: null

  checkpoint_dir: checkpoints/diffdec_dmd

  sample_interval: 50
  save_interval: 200

  teacher_vae_ckpt: /mnt/data/checkpoints/owl_vaes/cod_128x_feats/cod_128x_feats_160k_ema.pt
  teacher_vae_cfg: configs/cod_128x_feats.yml

  teacher_diff_ckpt: ./checkpoints/diffdec/step_100000.pt
  teacher_diff_cfg: configs/diffdec_dcae.yml

  student_diff_ckpt: ./checkpoints/diffdec_ode_tune/step_3000.pt

  latent_scale: 0.7
  ldm_scale: 0.4552

  update_ratio: 5

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: diffdec_dmd
