model:
  model_id: diff_dec
  sample_size: [16,16]
  channels: 32
  latent_size: 8
  latent_channels: 128
  patch_size: 1

  n_layers: 28
  n_heads: 24
  d_model: 1536

  causal: false
  mimetic_init: false
  block_size: null

train:
  trainer_id: diff_dec
  data_id: s3_cod_features
  data_kwargs:
    bucket_name: cod-raw-360p-30fs
    prefix: rgb-depth-flow
    include_flow: true
    include_depth: true

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [core.proj_in, core.proj_out]

  scheduler: null

  checkpoint_dir: checkpoints/diffdec

  sample_interval: 1000
  save_interval: 10000

  teacher_ckpt: /mnt/data/checkpoints/owl_vaes/cod_128x_feats/cod_128x_feats_160k_ema.pt
  teacher_cfg: configs/cod_128x_feats.yml

  latent_scale: 0.7
  ldm_scale: 0.4552

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: diffdec_tune
