model:
  model_id: distill_vae
  sample_size: [360,640]
  channels: 3
  latent_size: 8
  latent_channels: 128

  ch_0: 96
  ch_max: 1536

  encoder_blocks_per_stage: [1, 1, 1, 1, 1]
  decoder_blocks_per_stage: [1, 1, 1, 1, 1]

  use_middle_block: false

train:
  trainer_id: distill_dec
  data_id: s3_cod_features
  data_kwargs:
    bucket_name: cod-raw-360p-30fs
    prefix: rgb-depth-flow
    include_flow: true
    include_depth: true
    
  target_batch_size: 128
  batch_size: 16

  epochs: 100

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  lpips_id: convnext
  loss_weights:
    lpips: 10.0
    gan: 0.0
    feature_matching: 0.0
    r12: 0.0
    dwt: 1.0
    l1: 1.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 1500
    min_lr: 3.0e-6

  checkpoint_dir: /mnt/data/checkpoints/owl_vaes/feats_tune
  output_path: /mnt/data/checkpoints/owl_vaes/feats_tune_output
  teacher_ckpt: /mnt/data/checkpoints/owl_vaes/cod_128x_feats/cod_128x_feats_160k_ema.pt
  teacher_cfg: configs/cod_128x_feats.yml
  resume_ckpt: null

  sample_interval: 500
  save_interval: 5000

  delay_adv: 20000
  warmup_adv: 5000
  use_teacher_decoder: false
  latent_scale: 1.0
  skip_ind: 5

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: feats_tune
