# Config for a simple 256 -> 16 autoencoder
model:
  model_id: dcae
  sample_size: 256
  channels: 3
  latent_size: 16
  latent_channels: 32

  noise_decoder_inputs: 0.05
  ch_0: 32
  ch_max: 128

  encoder_blocks_per_stage: [2, 2, 2, 2]
  decoder_blocks_per_stage: [2, 2, 2, 2]

train:
  trainer_id: rec
  data_id: local_imagenet_256

  target_batch_size: 32
  batch_size: 8

  epochs: 200

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 0.01
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys:
      [encoder.conv_in, encoder.conv_out, decoder.conv_in, decoder.conv_out]

  loss_weights:
    latent_reg: 1.0e-5
    lpips: 0.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 3000
    min_lr: 1.0e-5

  checkpoint_dir: checkpoints/2d_128x

  sample_interval: 1000
  save_interval: 10000

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: 16x_imagenet
