model:
  model_id: dcae
  discriminator:
    model_id: freq
    ch_0: 96
    ch_max: 1536
    sample_size: [360, 640]
    blocks_per_stage: 1

  sample_size: [360,640]
  channels: 3
  latent_size: 4
  latent_channels: 128

  ch_0: 256
  ch_max: 2048

  encoder_blocks_per_stage: [4, 4, 4, 4, 4, 4, 4]
  decoder_blocks_per_stage: [4, 4, 4, 4, 4, 4, 4]

train:
  trainer_id: dec_tune_v2
  data_id: s3_cod
  data_kwargs:
    bucket_name: cod-raw-360p-30fs
    prefix: raw/01
    
  target_batch_size: 32
  batch_size: 4

  epochs: 100

  opt: AdamW
  opt_kwargs:
    lr: 3.0e-5
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  lpips_id: convnext
  loss_weights:
    lpips: 10.0
    gan: 0.1
    feature_matching: 1.0
    r12: 10.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 1500
    min_lr: 3.0e-6

  checkpoint_dir: checkpoints/cod_128x_tune
  teacher_ckpt: checkpoints/cod_128x/step_120000.pt
  teacher_cfg: configs/cod_128x.yml
  resume_ckpt: null #checkpoints/cod_128x_tune/step_5000.pt

  sample_interval: 500
  save_interval: 5000

  delay_adv: 5000
  warmup_adv: 5000
  use_teacher_decoder: true
  latent_scale: 1.0

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: 128x_cod_tune
