model:
  model_id: diff_dec
  sample_size: [360, 640]
  channels: 3
  latent_size: 4
  latent_channels: 128
  patch_size: 32

  n_layers: 12
  n_heads: 12
  d_model: 384

  causal: false
  mimetic_init: false

train:
  trainer_id: diff_dec
  data_id: s3_imagenet

  target_batch_size: 32
  batch_size: 16

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 1.0e-4
    eps: 1.0e-15
    betas: [0.9, 0.95]
    weight_decay: 1.0e-4

  loss_weights:
    latent_reg: 1.0e-6
    lpips: 0.0
    adv: 0.2

  delay_adv: 0
  warmup_adv: 500

  scheduler: null

  checkpoint_dir: checkpoints/v0

  sample_interval: 1000
  save_interval: 10000

  teacher_ckpt: checkpoints/v0/step_10000.pt
  teacher_cfg: configs/simple_16x.yml

  latent_scale: 0.465

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: v0
