model:
  model_id: diff_dec
  sample_size: [16,16]
  channels: 32
  latent_size: 8
  latent_channels: 64
  patch_size: 1

  n_layers: 14
  n_heads: 24
  d_model: 1536

  causal: false
  mimetic_init: false
  block_size: null

train:
  trainer_id: diffdec_ode_tune
  data_id: s3_cod_features
  data_kwargs:
    bucket_name: cod-raw-360p-30fs
    prefix: rgb-depth-flow

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [core.proj_in, core.proj_out]

  scheduler: null

  checkpoint_dir: checkpoints/diffdec_c64_ode_tune_tiny

  sample_interval: 1000
  save_interval: 1000

  teacher_vae_ckpt: cod_64x_depth_distill_enc.pt
  teacher_vae_cfg: configs/cod_64x_depth_v2_distill_enc.yml

  teacher_diff_ckpt: ./checkpoints/diffdec_c64/step_55000.pt
  teacher_diff_cfg: configs/diffdec_depth_c64.yml

  latent_scale: 0.87
  ldm_scale: 0.4552
  subsample: 0.25

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: diffdec_ode_tune
